######################################################################
# Automatically generated by qmake (2.01a) Thu Nov 1 17:14:42 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += corda.hpp core.hpp matrix.hpp
FORMS += corda.ui
SOURCES += corda.cpp core.cpp main.cpp matrix.cpp
